### ISSUE TITLE
Time stamps of sensor data - what's the sampling rate?

### ISSUE THREAD

**Issue by heiko-holz** [freezed-or-frozen/pymb1a#1]
Hey @freezed-or-frozen ,
I don't know another way to reach you other than this since the GadgetBridge discussion has been shut down ;)

I wanted to ask if you know anything about the sampling rate of the MiBand 1A or how to get time stamps of the sensor values.

Best,

Heiko

**Comment by freezed-or-frozen** [comment]
Hi @Heikofant ,

as far as I know MiBand 1A seems to retreive accelerometer data at 25Hz from -2g to +2g. I read this values from the ADXL362 datasheet and real mesurements did with pymb1a confirm it. Main processor which is a DA14580 SoC communicates with accelerometer thru SPI.

Timestamps should be recorded with other XYZ data in CSV. Have a look at the record_sensor_data() method. But sometimes MiBand 1A return two sets of XYZ data with the same timestamp...

I hope it can help you.

Have a nice day.

**Comment by heiko-holz** [comment]
@freezed-or-frozen 
thanks for your response!
I couldn't find timestamps that are transmitted with the sensor data.
I found 
`#millis = int(round(time.time() * 1000))`
which basically just takes the system time.
Do I get the real time stamp by multiplying `counter * 25` ?

**Comment by freezed-or-frozen** [comment]
Hi @Heikofant ,

you are right, timestamp is just compute from system time. No time information from MiBand raw data. I guess that accelerometer data are retreived at 25Hz (evidences from datasheet and measurements).

Have a nice day.
